[package]
name = "clock_tonic"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = { version = "0.10", features = ["tls", "tls-roots"] }
prost = "0.12"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
chrono = "0.4.31"

[build-dependencies]
tonic-build = "0.10"